name: xsim
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  geolocator: ^10.1.0
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.3
  firebase_auth: ^5.7.0
  intl: ^0.20.2
  blue_thermal_printer: ^1.2.3
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_commons: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Añadimos las herramientas de generación
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# CONFIGURACIÓN DEL ICONO DE LA APP
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  # Si tu icono tiene fondo transparente, puedes poner un color aquí:
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

# CONFIGURACIÓN DE LA PANTALLA DE CARGA (SPLASH)
flutter_native_splash:
  color: "#ffffff" # Cambia este hex por el color de fondo que desees
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/